[program:habeshahomes-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/habeshahomes/artisan queue:work redis --sleep=3 --tries=3 --max-time=3600 --timeout=120
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=4
redirect_stderr=true
stdout_logfile=/var/www/habeshahomes/storage/logs/worker.log
stopwaitsecs=3600

[program:habeshahomes-scheduler]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/habeshahomes/artisan schedule:work
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/habeshahomes/storage/logs/scheduler.log
